## Pandas

In [4]:
with open("C:\\python\\movie.csv") as data_file:
    data = data_file.readlines(1)
    print(data)

['color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes\n']

In [3]:
with open('data/movie.csv') as data_file:
    data = data_file.read()
    print(data)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 486261: character maps to <undefined>

In [6]:
import pandas as pd

In [7]:
movies = pd.read_csv('data/movie.csv')
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [ ]:
# 0, 1, 2, 3, 4 ... indexes / Axis 0
# color, director_name, num_critic_for_reviews ... columns / Axis 1
# Color, James Cameron ... values

In [11]:
movies.head() #by default first 5 values

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [12]:
movies.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [13]:
movies.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [14]:
movies.tail(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [15]:
columns = movies.columns
columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [16]:
values = movies.values
values

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [17]:
index = movies.index
index

RangeIndex(start=0, stop=4916, step=1)

In [18]:
print(type(columns))
print(type(values))
print(type(index))

<class 'pandas.core.indexes.base.Index'>
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.range.RangeIndex'>

In [ ]:
#DataFrame
#Series

In [20]:
type(movies)

pandas.core.frame.DataFrame

In [21]:
type(movies['content_rating'])

pandas.core.series.Series

In [22]:
movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [24]:
movies.dtypes.value_counts()

float64    13
object     12
int64       3
Name: count, dtype: int64

In [25]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   object
 1   director_name              4814 non-null   object
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object
 10  actor_1_name               4909 non-null   object
 11  movie_title                4916 non-null   object
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   object
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   object
 17  movie_imdb_link            4916 non-null   object
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4902 non-null   object
 20  country                    4911 non-null   object
 21  content_rating             4616 non-null   object
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [26]:
pd.Series(['Apple', None, 'Pear'])

0    Apple
1     None
2     Pear
dtype: object

In [27]:
movies.head(6)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000

In [31]:
import numpy as np

In [36]:
pd.Series(['Apple', None, 'Pear', np.nan, 'Grape'])

0    Apple
1     None
2     Pear
3      NaN
4    Grape
dtype: object

In [37]:
pd.Series(['Apple', None, 'Pear', np.nan, 'Grape']).dtypes

dtype('O')

In [ ]:
movies['director_name'] #shunaqa qilib alohida bitta columnni ajratib olishimiz mumkin
movies.director_name

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [41]:
movies.director_name

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [46]:
movies[['director_name', 'color']]

          director_name  color
0         James Cameron  Color
1        Gore Verbinski  Color
2            Sam Mendes  Color
3     Christopher Nolan  Color
4           Doug Walker    NaN
...                 ...    ...
4911        Scott Smith  Color
4912                NaN  Color
4913   Benjamin Roberds  Color
4914        Daniel Hsia  Color
4915           Jon Gunn  Color

[4916 rows x 2 columns]

In [47]:
type(movies['director_name'])

pandas.core.series.Series

In [48]:
movies['director_name'].dtype

dtype('O')

In [ ]:
type(movies[['director_name', 'color']]) #bu berilgan narsaning o'zining data typeni  chiqarib beradi 
movies['director_name'].dtype #bu ichidan chiqaryotgan dataning typeni chiqarib beradi

pandas.core.frame.DataFrame

In [ ]:
movies['director_name'].size #bu rowlari sonini chiqarib beradi

4916

In [51]:
movies['director_name'].name

'director_name'

In [52]:
movies['director_name'].unique()

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes', ...,
       'Scott Smith', 'Benjamin Roberds', 'Daniel Hsia'], dtype=object)

In [53]:
director = movies['director_name']

In [54]:
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

In [60]:
movies.sample(n=5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2718,Color,Gilles Paquet-Brenner,136.0,111.0,15.0,121.0,Aidan Quinn,1000.0,7691700.0,Drama|War,...,73.0,French,France,PG-13,10000000.0,2010.0,767.0,7.5,2.35,0
2729,Black and White,Jon Turteltaub,39.0,98.0,226.0,496.0,Leon,953.0,68856263.0,Adventure|Comedy|Family|Sport,...,97.0,English,USA,PG,15000000.0,1993.0,730.0,6.9,1.85,0
2176,Color,Jason Friedberg,122.0,82.0,82.0,354.0,Dave Foley,759.0,36658108.0,Comedy,...,187.0,English,USA,PG-13,20000000.0,2010.0,401.0,3.5,1.85,16000
3631,Color,David F. Sandberg,159.0,81.0,26.0,300.0,Amiah Miller,2000.0,56536016.0,Horror,...,95.0,English,USA,PG-13,4900000.0,2016.0,509.0,6.9,2.35,0
1234,Color,Clint Eastwood,249.0,134.0,16000.0,235.0,Steve Schirripa,880.0,47034272.0,Biography|Drama|Music|Musical,...,190.0,English,USA,R,40000000.0,2014.0,413.0,6.9,2.35,16000

In [62]:
director.value_counts()

director_name
Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
John Putch           1
Luca Guadagnino      1
Sam Fell             1
Dan Fogelman         1
Daniel Hsia          1
Name: count, Length: 2397, dtype: int64

In [ ]:
fb_likes = movies['actor_1_facebook_likes']
fb_likes.max()
fb_likes.mean() #bu o'rtachasini chiqarib beradi 
fb_likes.describe() #bu by defauly eng kerakli statistikalarini chiqarib beradi max ,min ,mean ..
director.isna()
director.isnull() #bu ikkitasiyam null yoki null emasligini tekshiradi va true yoki fasle chiqaradi

In [68]:
fb_likes.max()

640000.0

In [70]:
fb_likes.mean()

6494.488490527602

In [71]:
fb_likes.describe()

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

In [72]:
director.isna()

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [73]:
director.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [74]:
director

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [ ]:
# class 17

with open("C:\\python\\movie.csv") as data_file:
    data = data_file.readlines(1)
    print(data) #bu oddiy o'qib olish 
#pandas 
import pandas as pd
movies = pd.read_csv('data/movie.csv') #shu shaklda pandas bilan datani o'qib olamiz

movies.head() #by default first 5 values boshidan chiqarib beradi rowlarni 

movies.tail(3) # bu ohiridan chiqarib beradi 

movies.columns # bu faqat columnlarni array shaklida chiqarib beradi

movies.values # bu tableni hisobga olmagan holda tabledaki hamma valueslarni chiqarib beradi 

#Dataframe bu pandasdagi table 
#Series bu bitta columnni o'ziga aytiladi 

#pandasda objectbu string datatype 

movies.dtypes.value_counts() # bu kod dtypes bo'yicha gruhlab sanab berishi

movies.info() # bu tableni null bo'lmagan barcha malumotlarni chiqarib beradi 


pd.Series('pd.Series(['Apple', None, 'Pear'])') #shu orqali series yasab olinadi yani bitta column 

None #degan datatype mavjud 

import pandas as np
pd.Series(['Apple', None, 'Pear', np.nan, 'Grape']) #shunaqa qilib nan  datatypeni qo'yiladi bu degan sqldagi Nullga teng 

movies['director_name'] #shunaqa qilib alohida bitta columnni ajratib olishimiz mumkin
movies.director_name #bu bilan faqat 1 ta colummnni chiqarib ola olamiz

type(movies[['director_name', 'color']]) #bu berilgan narsaning o'zining data typeni  chiqarib beradi 
movies['director_name'].dtype #bu ichidan chiqaryotgan dataning typeni chiqarib beradi 

movies['director_name'].size #bu rowlari sonini chiqarib beradi 

movies['director_name'].name #column nameni chiqarib beradi 

movies['director_name'].unique() #arrayda unique datalarni chiqarib beradi 

movies.sample(n=5) #bu datalarni ichidan sample random rowlarni chiqarib  beradi 

director=movies['director_name']
director.value_counts()# bu datalarni necha marta kelganini chiqarib beradi yani directorname bo'yich group by qilib beradi 

fb_likes = movies['actor_1_facebook_likes']
fb_likes.max()
fb_likes.mean() #bu o'rtachasini chiqarib beradi 
fb_likes.describe() #bu by defauly eng kerakli statistikalarini chiqarib beradi max ,min ,mean ..
director.isna()
director.isnull() #bu ikkitasiyam null yoki null emasligini tekshiradi va true yoki fasle chiqaradi 

director.fillna(0) #bu datalari ichida null dataga 0 qo'yib chiqarib beradi lekin variabledagai dataga tasir qilmaydi 
director = director.fillna(0) #bu esa tasir  qiladi

fb_likes.count() #bu null bo'lmagan roqlarni sanaydi 
fb_likes.fillna(0).count() #hamma rowlarni sanaydi

fb_likes.dropna()#bu null yo'q rowlarni chiqarib beradi null larni chiqarib yuboradi rowlarini 
fb_likes=fb_likes.dropna() #bunday qilgandan keyingina tasir qiladi asosiy dataga 

imdb_score = movies['imdb_score']
imdb_score
imdb_score + 1 #bunday qilsak arraylar kabi hamma malumotga qo'shib beradi 

movies[movies['imdb_score'] > 8] #bu orqali filter beramiz

money.sub(15, fill_value=8) #ayrib beraid fill_value buyerda agar null data bo'lsa uni nolga o'zgartiib berishadi 

movies = movies.rename(columns={'director_name':'director', 'num_critic_for_reviews':'critic reviews'}) #columnlarning nomini ozgarturib beradi 

fb_likes.fillna(0).astype()#shunaqa qilib typelarini convert qilishimiz mumkin 

17.30

In [ ]:
director = director.fillna(0).astype(int)

In [78]:
director

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...
4911          Scott Smith
4912                    0
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [81]:
fb_likes.fillna(0).count()

4916

In [82]:
fb_likes.dropna()

0        1000.0
1       40000.0
2       11000.0
3       27000.0
4         131.0
         ...
4911      637.0
4912      841.0
4913        0.0
4914      946.0
4915       86.0
Name: actor_1_facebook_likes, Length: 4909, dtype: float64

In [83]:
fb_likes

0        1000.0
1       40000.0
2       11000.0
3       27000.0
4         131.0
         ...
4911      637.0
4912      841.0
4913        0.0
4914      946.0
4915       86.0
Name: actor_1_facebook_likes, Length: 4916, dtype: float64

In [ ]:
imdb_score = movies['imdb_score']
imdb_score
imdb_score + 1

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ...
4911    7.7
4912    7.5
4913    6.3
4914    6.3
4915    6.6
Name: imdb_score, Length: 4916, dtype: float64

In [86]:
imdb_score + 1

0       8.9
1       8.1
2       7.8
3       9.5
4       8.1
       ...
4911    8.7
4912    8.5
4913    7.3
4914    7.3
4915    7.6
Name: imdb_score, Length: 4916, dtype: float64

In [89]:
movies[movies['imdb_score'] > 8]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
43,Color,Lee Unkrich,453.0,103.0,125.0,721.0,John Ratzenberger,15000.0,414984497.0,Adventure|Animation|Comedy|Family|Fantasy,...,733.0,English,USA,G,200000000.0,2010.0,1000.0,8.3,1.85,30000
58,Color,Andrew Stanton,421.0,98.0,475.0,522.0,Fred Willard,1000.0,223806889.0,Adventure|Animation|Family|Sci-Fi,...,1043.0,English,USA,G,180000000.0,2008.0,729.0,8.4,2.35,16000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,Color,Cary Bell,NaN,78.0,0.0,0.0,Stacie Evans,0.0,NaN,Documentary,...,1.0,English,USA,NaN,180000.0,2014.0,0.0,8.7,NaN,88
4815,Color,Bill Melendez,43.0,25.0,36.0,27.0,Bill Melendez,39.0,NaN,Animation|Comedy|Family,...,126.0,English,USA,TV-G,150000.0,1965.0,36.0,8.4,1.33,0
4822,Color,Amal Al-Agroobi,NaN,62.0,58.0,NaN,NaN,NaN,NaN,Documentary|Family,...,NaN,Arabic,United Arab Emirates,NaN,125000.0,2013.0,NaN,8.2,NaN,54
4846,Color,Sut Jhally,16.0,80.0,3.0,0.0,Seth Ackerman,103.0,NaN,Documentary,...,13.0,English,USA,NaN,70000.0,2004.0,0.0,8.3,NaN,110
4875,Color,Martin Scorsese,71.0,117.0,17000.0,476.0,Levon Helm,725.0,321952.0,Documentary|Music,...,113.0,English,USA,PG,NaN,1978.0,572.0,8.2,1.85,0

In [2]:
money = pd.Series([100, 20, None])
money

NameError: name 'pd' is not defined

In [ ]:
money.sub(15, fill_value=0)

NameError: name 'money' is not defined

In [100]:
secondmoney = pd.Series([50, 10, 4, 30])
secondmoney

0    50
1    10
2     4
3    30
dtype: int64

In [103]:
money + secondmoney

0    150.0
1     30.0
2      NaN
3      NaN
dtype: float64

In [109]:
fb_likes.fillna(0).astype(int)

0        1000
1       40000
2       11000
3       27000
4         131
        ...
4911      637
4912      841
4913        0
4914      946
4915       86
Name: actor_1_facebook_likes, Length: 4916, dtype: int32

In [112]:
movies = movies.rename(columns={'director_name':'director', 'num_critic_for_reviews':'critic reviews'})

In [113]:
movies

,color,director,critic reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [119]:
movies['viewed'] = 1

In [120]:
movies

,color,director,critic reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,viewed
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,1
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,1
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,1
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,1
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,1
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,1
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,1
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,1
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,1

In [128]:
movies.drop(columns='viewed', inplace=True, errors='ignore')

In [129]:
movies.head(3)

,color,director,critic reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

In [137]:
fname = ['McAtee', 'Fede', 'Richard', 'Weah']
lname = ['Freddie', 'Valve', 'Stark', 'Timoty']
birth = [2005, 1996, 1985, np.nan]

people = pd.DataFrame({'FirstName':fname, 'LastName':lname, 'BirthDate':birth})
people

  FirstName LastName  BirthDate
0    McAtee  Freddie     2005.0
1      Fede    Valve     1996.0
2   Richard    Stark     1985.0
3      Weah   Timoty        NaN

In [139]:
movies[movies.director == 'James Cameron']

,color,director,critic reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
285,Color,James Cameron,210.0,153.0,0.0,539.0,Jenette Goldstein,780.0,204843350.0,Action|Sci-Fi,...,983.0,English,USA,R,102000000.0,1991.0,604.0,8.5,2.35,13000
288,Color,James Cameron,94.0,141.0,0.0,618.0,Tia Carrere,2000.0,146282411.0,Action|Comedy|Thriller,...,351.0,English,USA,R,115000000.0,1994.0,1000.0,7.2,2.35,0
599,Color,James Cameron,82.0,171.0,0.0,638.0,Todd Graff,2000.0,54222000.0,Adventure|Drama|Sci-Fi|Thriller,...,380.0,English,USA,PG-13,69500000.0,1989.0,650.0,7.6,2.35,0
2455,Color,James Cameron,250.0,154.0,0.0,604.0,Carrie Henn,2000.0,85200000.0,Action|Adventure|Sci-Fi,...,1076.0,English,USA,R,18500000.0,1986.0,626.0,8.4,1.85,18000
3508,Color,James Cameron,204.0,107.0,0.0,255.0,Brian Thompson,2000.0,38400000.0,Action|Sci-Fi,...,692.0,English,UK,R,6500000.0,1984.0,663.0,8.1,1.85,13000

In [143]:
movies[movies['director_facebook_likes'] == movies['director_facebook_likes'].max()]['director']

3603    Joseph Gordon-Levitt
Name: director, dtype: object

In [148]:
#1. Find the average temperature and the maximum one
#2. What was the weather condition on Monday
#3. What was the temperature on Friday in Farenheit

#20. +3

weather = pd.read_csv('weather_data.csv')
#1
print(weather['temp'].mean())
print(weather['temp'].max())

#2
print(weather[weather.day == 'Monday']['condition'])

#3
print(weather[weather.day == 'Friday']['temp']*9/5+32)

14.0
20
0    Sunny
Name: condition, dtype: object
4    66.2
Name: temp, dtype: float64